# .readthedocs.yaml
version: 2
build:
    os: "ubuntu-22.04"
    tools:
        python: "3.11"

sphinx:
    configuration: docs/source/source/conf.py

python:
    install:
        - requirements: docs/requirements.txt
